### PR TITLE
Adding rollup 3.15.0 version

### PR DESCRIPTION
**Pull request by vsrikrishna32**

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]

**Comment by gregmagolan** [comment]
> @alexeagle @gregmagolan . Does this look ok?

The addition of the new version looks right but looks like there were breaking changing in this version of rollup that is breaking test cases. By default the rule set tests against the latest version available in versions.bzl.

**Comment by vsrikrishna32** [comment]
Sure, I can take a crack at it! Thanks

**Comment by vsrikrishna32** [comment]
I need to reopen the PR since my git config is messed up for the first commit and can't sign CLA. Sorry about the trouble.

**Comment by vsrikrishna32** [comment]
https://github.com/aspect-build/rules_rollup/pull/71

**Pull request closed without merging**
